#!/usr/bin/env python3
"""Validate an Episode 4 found-clip manifest before source intake promotion.

This command checks the editable watched/source found-clip manifest generated by
`build_episode4_watched_source_recovery_packet.py`. It answers one narrow
question: which cue candidates point at real files and are safe to hand to the
source-intake/review path?

Safety boundary: validation artifacts only. This command never imports clips,
writes timeline/session state, renders exports, publishes, deletes, overwrites
previous packet versions, or mutates source media.
"""
from __future__ import annotations

import argparse
import html
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

RELEASE_ROOT = Path("/Volumes/My Passport/Episode_and_Shorts_Test")
RECOVERY_POINTER = RELEASE_ROOT / "review-board/episode4-watched-source-recovery-packet/latest-episode4-watched-source-recovery-packet.json"
OUT_ROOT = RELEASE_ROOT / "review-board/episode4-found-clip-manifest-validation"
LATEST_POINTER = OUT_ROOT / "latest-episode4-found-clip-manifest-validation.json"
SCHEMA = "quipsly.episode4-found-clip-manifest-validation.v1"


def iso_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S-%f-found-clip-manifest-validation")


def esc(value: Any) -> str:
    return html.escape(str(value if value is not None else ""))


def as_text(value: Any, fallback: str = "") -> str:
    if value is None:
        return fallback
    text = str(value).strip()
    return text if text else fallback


def as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def dict_list(value: Any) -> list[dict[str, Any]]:
    return value if isinstance(value, list) and all(isinstance(item, dict) for item in value) else []


def load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return payload if isinstance(payload, dict) else {}
    except Exception:
        return {}


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def truth() -> dict[str, Any]:
    return {
        "validationArtifactsOnly": True,
        "sourceFilesReadOnly": True,
        "sourceFilesMutated": False,
        "sourceFilesMovedOrRenamed": False,
        "clipsImported": False,
        "timelineDecisionsWritten": False,
        "branchMetadataWritten": False,
        "exportsRendered": False,
        "externalPublishing": False,
        "versionsOverwritten": False,
        "filesDeleted": False,
    }


def resolve_manifest_path(args: argparse.Namespace) -> Path:
    if args.manifest:
        return args.manifest
    pointer = load_json(args.recovery_pointer)
    target = as_text(pointer.get("foundClipManifestTemplatePath"))
    return Path(target) if target else Path()


def candidate_file_path(candidate: dict[str, Any]) -> tuple[str, str]:
    explicit = as_text(candidate.get("candidateFilePath"))
    if explicit:
        return explicit, "candidateFilePath"
    dropbox = as_text(candidate.get("dropboxPath"))
    suggested = as_text(candidate.get("suggestedFilename"))
    if dropbox and suggested:
        return str(Path(dropbox) / suggested), "dropboxPath+suggestedFilename"
    return "", "missing"


def row_status(candidate: dict[str, Any], path_text: str) -> tuple[str, str, bool]:
    cue_id = as_text(candidate.get("cueId"))
    confidence = as_text(candidate.get("confidence"), "unknown").casefold()
    promotion = bool(candidate.get("promotionAllowed"))
    if not cue_id:
        return "blocked", "Cue ID is missing.", False
    if not path_text:
        return "waiting-for-file", "No candidateFilePath or dropbox/suggestedFilename path is available.", False
    path = Path(path_text)
    if not path.exists():
        return "waiting-for-file", "Candidate file is not present yet.", False
    if not path.is_file():
        return "blocked", "Candidate path exists but is not a file.", False
    if confidence in {"unknown", "low", "uncertain", ""}:
        return "needs-human-confidence", "File exists, but confidence is not high enough for promotion.", False
    if not promotion:
        return "ready-for-intake-review", "File exists and confidence is set; promotion is still disabled until intake/review confirms the match.", True
    return "review-before-promotion", "File exists and manifest says promotionAllowed=true; still require intake and cue-match review before writing timeline metadata.", True


def validate_candidate(candidate: dict[str, Any]) -> dict[str, Any]:
    path_text, path_source = candidate_file_path(candidate)
    status, reason, ready = row_status(candidate, path_text)
    path = Path(path_text) if path_text else Path()
    size = path.stat().st_size if path.exists() and path.is_file() else None
    return {
        "cueId": as_text(candidate.get("cueId")),
        "status": status,
        "readyForSourceIntakeReview": ready,
        "reason": reason,
        "candidateFilePath": path_text,
        "pathSource": path_source,
        "fileExists": path.exists() if path_text else False,
        "fileSizeBytes": size,
        "clipTitleOrDescription": as_text(candidate.get("clipTitleOrDescription")),
        "sourceUrlOrFilePath": as_text(candidate.get("sourceUrlOrFilePath")),
        "sourceInOut": as_text(candidate.get("sourceInOut")),
        "whyItBelongsHere": as_text(candidate.get("whyItBelongsHere")),
        "confidence": as_text(candidate.get("confidence"), "unknown"),
        "promotionAllowedInManifest": bool(candidate.get("promotionAllowed")),
        "proposedRole": as_text(candidate.get("proposedRole"), "watched-source-clip"),
        "importIntent": as_text(candidate.get("importIntent"), "hold-until-intake-confirms-cue-match"),
        "syncIntent": as_text(candidate.get("syncIntent"), "candidate-insert-near-cue-window"),
        "nextAction": next_action_for(status, candidate),
    }


def next_action_for(status: str, candidate: dict[str, Any]) -> str:
    cue_id = as_text(candidate.get("cueId"), "this cue")
    suggested = as_text(candidate.get("suggestedFilename"), f"{cue_id}-short-description.mp4")
    dropbox = as_text(candidate.get("dropboxPath"), "the watched/source dropbox")
    if status == "ready-for-intake-review":
        return "Run source intake, review the cue match, then decide whether to promote clip-weave metadata."
    if status == "review-before-promotion":
        return "Run source intake and cue-match review before honoring promotionAllowed."
    if status == "needs-human-confidence":
        return "Listen/watch the cue again and set confidence to medium/high only if this is the real watched/source clip."
    if status == "waiting-for-file":
        return f"Copy the matching file into {dropbox} as {suggested}, or set candidateFilePath to the real file."
    return "Fix the manifest row before intake review."


def counts_for(rows: list[dict[str, Any]]) -> dict[str, Any]:
    statuses: dict[str, int] = {}
    for row in rows:
        statuses[row["status"]] = statuses.get(row["status"], 0) + 1
    return {
        "candidates": len(rows),
        "readyForSourceIntakeReview": sum(1 for row in rows if row.get("readyForSourceIntakeReview")),
        "fileExists": sum(1 for row in rows if row.get("fileExists")),
        "waitingForFile": statuses.get("waiting-for-file", 0),
        "needsHumanConfidence": statuses.get("needs-human-confidence", 0),
        "blocked": statuses.get("blocked", 0),
        "statuses": statuses,
    }


def render_markdown(packet: dict[str, Any]) -> str:
    counts = as_dict(packet.get("counts"))
    lines = [
        "# Episode 4 found-clip manifest validation",
        "",
        f"Generated: `{packet.get('generatedAt')}`",
        f"Status: `{packet.get('status')}`",
        f"Manifest: `{packet.get('manifestPath')}`",
        "",
        "## Summary",
        "",
        f"- Candidates: `{counts.get('candidates', 0)}`",
        f"- File exists: `{counts.get('fileExists', 0)}`",
        f"- Ready for source-intake review: `{counts.get('readyForSourceIntakeReview', 0)}`",
        f"- Waiting for file: `{counts.get('waitingForFile', 0)}`",
        f"- Needs human confidence: `{counts.get('needsHumanConfidence', 0)}`",
        f"- Blocked rows: `{counts.get('blocked', 0)}`",
        "",
        "## Candidate rows",
        "",
    ]
    for row in dict_list(packet.get("rows")):
        lines.extend(
            [
                f"### {row.get('cueId') or 'missing cue'}",
                "",
                f"- Status: `{row.get('status')}`",
                f"- Reason: {row.get('reason')}",
                f"- File: `{row.get('candidateFilePath') or 'missing'}`",
                f"- Confidence: `{row.get('confidence')}`",
                f"- Ready for intake review: `{row.get('readyForSourceIntakeReview')}`",
                f"- Next: {row.get('nextAction')}",
                "",
            ]
        )
    lines.extend(
        [
            "## Safety boundary",
            "",
            "This validation packet does not import clips, mutate source media, write timeline metadata, render exports, or publish anything.",
            "",
        ]
    )
    return "\n".join(lines)


def render_html(packet: dict[str, Any]) -> str:
    counts = as_dict(packet.get("counts"))
    rows = []
    for row in dict_list(packet.get("rows")):
        rows.append(
            "<article>"
            f"<p class='meta'>{esc(row.get('status'))}</p>"
            f"<h2>{esc(row.get('cueId') or 'missing cue')}</h2>"
            f"<p>{esc(row.get('reason'))}</p>"
            f"<p><strong>File:</strong> <code>{esc(row.get('candidateFilePath') or 'missing')}</code></p>"
            f"<p><strong>Confidence:</strong> {esc(row.get('confidence'))} · <strong>Ready:</strong> {esc(row.get('readyForSourceIntakeReview'))}</p>"
            f"<p><strong>Next:</strong> {esc(row.get('nextAction'))}</p>"
            "</article>"
        )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Episode 4 found-clip manifest validation</title>
  <style>
    :root {{ color-scheme: dark; --bg:#10170f; --panel:#1d291b; --ink:#f6eed3; --muted:#bdae8a; --moss:#6ec98b; --honey:#f0c95a; --clay:#d66b55; }}
    body {{ margin:0; padding:32px; font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif; background: radial-gradient(circle at top left, #203625, var(--bg)); color:var(--ink); }}
    .hero, article {{ max-width:1080px; margin:0 auto 14px; padding:20px; border-radius:22px; background:rgba(29,41,27,.9); border:1px solid rgba(240,201,90,.24); }}
    h1 {{ margin:.2rem 0; font-size:34px; }} h2 {{ margin:.2rem 0; }}
    .stats {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin-top:16px; }}
    .stat {{ padding:12px; border-radius:16px; background:rgba(255,255,255,.06); }}
    .stat b {{ display:block; color:var(--honey); font-size:22px; }}
    .meta {{ color:var(--honey); text-transform:uppercase; letter-spacing:.12em; font-size:12px; font-weight:800; }}
    code {{ color:var(--moss); white-space:pre-wrap; }} p {{ color:var(--muted); }}
  </style>
</head>
<body>
  <section class="hero">
    <p class="meta">Quipsly Episode 4</p>
    <h1>Found-clip manifest validation</h1>
    <p>This is a preflight for recovered watched/source clips. It does not import clips or write timeline metadata.</p>
    <p><strong>Manifest:</strong> <code>{esc(packet.get('manifestPath'))}</code></p>
    <div class="stats">
      <div class="stat"><b>{esc(counts.get('candidates', 0))}</b> candidates</div>
      <div class="stat"><b>{esc(counts.get('fileExists', 0))}</b> files exist</div>
      <div class="stat"><b>{esc(counts.get('readyForSourceIntakeReview', 0))}</b> ready</div>
      <div class="stat"><b>{esc(counts.get('waitingForFile', 0))}</b> waiting</div>
    </div>
  </section>
  {''.join(rows)}
</body>
</html>
"""


def build_packet(args: argparse.Namespace) -> dict[str, Any]:
    manifest_path = resolve_manifest_path(args)
    manifest = load_json(manifest_path) if manifest_path and manifest_path.exists() else {}
    candidates = dict_list(manifest.get("candidates"))
    rows = [validate_candidate(candidate) for candidate in candidates]
    counts = counts_for(rows)
    status = "episode4-found-clip-validation-ready" if rows else "episode4-found-clip-validation-empty"
    if counts["readyForSourceIntakeReview"]:
        next_action = "Run episode4-source-clip-intake, then review cue matches before any clip-weave promotion."
    elif counts["waitingForFile"]:
        next_action = "Recover watched/source files or fill candidateFilePath values, then rerun this validation."
    else:
        next_action = "Fix manifest rows or regenerate the watched/source recovery packet."
    return {
        "schema": SCHEMA,
        "generatedAt": iso_now(),
        "status": status,
        "episode": "episode-4",
        "manifestPath": str(manifest_path) if manifest_path else "",
        "manifestExists": manifest_path.exists() if manifest_path else False,
        "rows": rows,
        "counts": counts,
        "nextSafestAction": next_action,
        "truth": truth(),
    }


def write_packet(packet: dict[str, Any]) -> dict[str, Any]:
    session_dir = OUT_ROOT / stamp()
    session_dir.mkdir(parents=True, exist_ok=True)
    json_path = session_dir / "episode4-found-clip-manifest-validation.json"
    markdown_path = session_dir / "episode4-found-clip-manifest-validation.md"
    html_path = session_dir / "index.html"
    packet.update({"sessionDir": str(session_dir), "jsonPath": str(json_path), "markdownPath": str(markdown_path), "htmlPath": str(html_path)})
    write_json(json_path, packet)
    markdown_path.write_text(render_markdown(packet), encoding="utf-8")
    html_path.write_text(render_html(packet), encoding="utf-8")
    write_json(
        LATEST_POINTER,
        {
            "schema": SCHEMA + ".pointer",
            "generatedAt": iso_now(),
            "status": packet.get("status"),
            "sessionDir": str(session_dir),
            "jsonPath": str(json_path),
            "markdownPath": str(markdown_path),
            "htmlPath": str(html_path),
            "manifestPath": packet.get("manifestPath"),
            "counts": packet.get("counts"),
            "nextSafestAction": packet.get("nextSafestAction"),
            "truth": packet.get("truth"),
        },
    )
    return packet


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, help="Editable found-clip manifest JSON to validate.")
    parser.add_argument("--recovery-pointer", type=Path, default=RECOVERY_POINTER)
    parser.add_argument("--json", action="store_true", help="Print JSON. This is the default.")
    parser.add_argument("--markdown", action="store_true", help="Print Markdown.")
    args = parser.parse_args()
    packet = write_packet(build_packet(args))
    if args.markdown:
        print(render_markdown(packet))
    else:
        print(json.dumps(packet, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
