substitutions:
  _REGION: us-central1
  _ARTIFACT_REPOSITORY: high-ground-studio
  _IMAGE_NAME: web
  _IMAGE_TAG: manual

steps:
  - id: build-web-image
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:latest
      - --cache=true
      - --cache-ttl=168h
      - --dockerfile=apps/web/Dockerfile

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
