substitutions:
  _REGION: us-central1
  _REPOSITORY: high-ground-studio
  _IMAGE_NAME: quipsly-schema
  _IMAGE_TAG: latest

steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - --cache=true
      - --cache-ttl=168h
      - --dockerfile=ops/quipsly-schema.Dockerfile

options:
  logging: CLOUD_LOGGING_ONLY
