substitutions:
  _REGION: us-central1
  _ARTIFACT_REPOSITORY: high-ground-studio
  _IMAGE_NAME: web
  _IMAGE_TAG: manual

steps:
  - id: build-web-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/web/Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_IMAGE_NAME}:${_IMAGE_TAG}
