-- The capture-group column used a database default while it was introduced so
-- existing CallRoom rows could be backfilled atomically. New room identities
-- are generated by Prisma, so remove the temporary database default once every
-- retained row has a stable UUID.
ALTER TABLE "CallRoom"
ALTER COLUMN "captureGroupId" DROP DEFAULT;

-- PostgreSQL truncated the original 76-character index identifier to 63
-- characters. Rename that physical index to Prisma's deterministic 63-character
-- identifier so migration history and the canonical schema compare exactly.
ALTER INDEX "ProviderRecordingCommand_expectedStorageBucket_expectedStorageO"
RENAME TO "ProviderRecordingCommand_expectedStorageBucket_expectedStor_idx";
