#!/usr/bin/env python3
"""Create a stable START_HERE entry point for an audio review baseline.

Timestamped artifacts are useful evidence, but reviewers need one obvious file
to open. This script writes stable Markdown and .command launchers in the
baseline folder. It does not approve audio, fail audio, render branches, upload
files, or mutate original media.
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def resolve_baseline_dir(input_path: Path) -> Path:
    if (input_path / "manifest.json").exists():
        return input_path.expanduser().resolve()
    nested = input_path / "work" / "conformed-production-baseline"
    if (nested / "manifest.json").exists():
        return nested.expanduser().resolve()
    raise FileNotFoundError(
        "Could not find manifest.json at "
        f"{input_path}/manifest.json or {nested}/manifest.json"
    )


def output_path(value: Any) -> str | None:
    if isinstance(value, str):
        return value
    if isinstance(value, dict):
        path = value.get("path")
        if isinstance(path, str):
            return path
    return None


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def file_line(label: str, path: str | None) -> str:
    return f"- {label}: `{path or 'not registered'}`"


def command_block(lines: list[str]) -> list[str]:
    return ["```bash", *lines, "```"]


def open_command(path: str | None, label: str) -> list[str]:
    if path:
        return ["open " + shell_quote(path)]
    return [f"echo 'Missing {label}; regenerate the review artifacts before approving audio.'"]


def build_markdown(report: dict[str, Any]) -> str:
    paths = report["paths"]
    commands = report["commands"]
    lines = [
        f"# START HERE: Episode 4 Audio Review",
        "",
        f"Generated: `{report['generatedAt']}`",
        "",
        "This is the stable front door for the current v006 audio review. It does not approve audio, fail audio, render branches, upload files, or mutate source media.",
        "",
        "## Current truth",
        "",
        f"- Baseline: `{report['baselineId']}`",
        f"- Approval status: `{report['approvalStatus']}`",
        f"- Package ready for human listen: `{str(report['packageReadyForHumanListen']).lower()}`",
        f"- Human listen still required: `{str(report['humanListenStillRequired']).lower()}`",
        f"- Branch inheritance ready: `{str(report['branchInheritanceReady']).lower()}`",
        f"- Branch render ready: `{str(report['branchRenderReady']).lower()}`",
        "",
        "## Do this first",
        "",
        "Open the producer command center. This is the calm front door for the whole review runway: current candidate, shortest listen path, smoothness proof, preservation proof, source-balance checks, dxRevive fallback state, action queue, and next safe actions.",
        "",
        *command_block(commands["openProducerCommandCenter"]),
        "",
        "Open the audio runway state. This is the compact current-state rollup: approval locks, gate result, unresolved requirements, handoff health, and the next safe action before anyone approves, branches, renders, uploads, or publishes.",
        "",
        *command_block(commands["openAudioRunwayState"]),
        "",
        "Open the listen proof coverage map. This is the minimum sufficient review route: which evidence to hear, which surfaces capture notes, and how each remaining partial or locked requirement can become pass, proof-needed, or scoped repair.",
        "",
        *command_block(commands["openListenProofCoverageMap"]),
        "",
        "Open the human approval preflight. This is the compact go/no-go check before routing a real listen decision: package integrity, branch locks, note inbox state, dxRevive fallback state, and next safe action.",
        "",
        *command_block(commands["openHumanApprovalPreflight"]),
        "",
        "Open the human listen decision front door. This is the stable route after listening: export or import notes, dry-run the decision bridge, record the guarded decision, then refresh the post-listen gates before any render.",
        "",
        *command_block(commands["openHumanListenDecisionFrontDoor"]),
        "",
        "Open the post-listen outcome router. This answers the after-listen question directly: keep waiting for human listen, route to v007 repair, refresh post-listen gates, or expose approved branch commands only when the manifest proves that is safe.",
        "",
        *command_block(commands["openPostListenOutcomeRouter"]),
        "",
        "Open the reviewer notes template. This is the stable place to capture or import human listen notes before any guarded approval, failure, or needs-proof decision is recorded.",
        "",
        *command_block(commands["openReviewerNotesTemplate"]),
        "",
        "Open the branch inheritance gate. It should stay blocked until a real human listen decision approves this spine, then become the post-approval gate for long-form and shorts branch renders.",
        "",
        *command_block(commands["openBranchInheritanceGate"]),
        "",
        "Open the branch render preflight. It stays blocked until approval and branch inheritance are ready, but it shows the exact long-form and shorts render commands that will become valid after the gates pass.",
        "",
        *command_block(commands["openBranchRenderPreflight"]),
        "",
        "Open the approval-path sandbox smoke. This proves the post-approval route in a sandbox only: approval, branch gate, branch-render preflight, and approved render command exposure there; real v006 stays locked.",
        "",
        *command_block(commands["openApprovalPathSmoke"]),
        "",
        "Open the unresolved requirement review. This turns the goal audit's partial and locked items into direct action lanes so you can see what needs ears, notes, returned bounces, another messy episode, or explicit approval.",
        "",
        *command_block(commands["openUnresolvedRequirementReview"]),
        "",
        "Open the audio production doctrine. This is the operating manual for the professional audio chain: source inventory, speaker-aware cleanup, dxRevive/manual fallback, mix/master, human listen, branch inheritance, and future noisy/outdoor episodes.",
        "",
        *command_block(commands["openAudioProductionDoctrine"]),
        "",
        "Open the transformation lineage ledger. This is the provenance map for what changed the sound, what evidence proves it, and which repair knob owns the next safe move. Use it before rerunning the chain blindly.",
        "",
        *command_block(commands["openAudioTransformationLineageLedger"]),
        "",
        "Open the transformation lineage smoke. This proves the lineage map can show complete evidence and missing evidence without moving real approval or branch locks.",
        "",
        *command_block(commands["openAudioTransformationLineageLedgerSmoke"]),
        "",
        "Open the stage control surface. This is the map of the whole audio workbench: raw sources, sync, speaker activity, cleanup, restoration, mix/master, human listen, and branch inheritance. Use it when you need to understand which knob belongs to which stage before touching anything.",
        "",
        *command_block(commands["openStageControlSurface"]),
        "",
        "Open the final-listen fast pass. This is the compact human route: one master player, the highest-value jump checks, local notes export, and no approval magic. Use it when the full review surface feels too sprawling.",
        "",
        *command_block(commands["openFinalListenFastPass"]),
        "",
        "If you export notes from the final-listen fast pass, route them through the fast-pass notes inbox. The inbox turns pass, proof, and repair notes into the unified post-review action queue without approving v006.",
        "",
        *command_block(commands["runFinalListenFastPassNotesInbox"]),
        "",
        "Open the platform loudness audit. This proves the WAV/M4A delivery copy against podcast and social reference profiles, while keeping YouTube/social as advisory instead of fake certainty.",
        "",
        *command_block(commands["openPlatformLoudnessAudit"]),
        "",
        "Open the broadcast polish scorecard. This gives the producer-level delivery view in one place: loudness, smoothness, source preservation, review readiness, and restoration-control risk. It is still machine evidence, not approval.",
        "",
        *command_block(commands["openBroadcastPolishScorecard"]),
        "",
        "Open the technical audition snippet pack. This turns the technical audition map into playable clips for channel balance, quiet-floor behavior, fatigue risk, and underpowered-speech checks.",
        "",
        *command_block(commands["openTechnicalAuditionSnippetPack"]),
        "",
        "If you export notes from the technical audition snippet pack, route them through the technical audition notes inbox. The inbox turns pass, proof, and repair notes into the unified post-review action queue without approving v006.",
        "",
        *command_block(commands["runTechnicalAuditionNotesInbox"]),
        "",
        "Open the smoothness proof pack. This turns dense edge/jump/pause markers into short listening clips, so the current smoothness concern can be proved by ear instead of by fear.",
        "",
        *command_block(commands["openSmoothnessProofPack"]),
        "",
        "If you export notes from the smoothness proof pack, route them through the smoothness notes inbox. The inbox turns pass, proof, and repair notes into the unified post-review action queue without approving v006.",
        "",
        *command_block(commands["runSmoothnessProofNotesInbox"]),
        "",
        "Open the producer-grade audio audit. This is the machine producer clipboard: score, risks, strengths, and jump buttons for the moments most likely to prove whether the spine feels natural. It focuses human listening but cannot approve the spine.",
        "",
        *command_block(commands["openProducerGradeAudit"]),
        "",
        "If you export notes from the producer-grade audit, route them through the producer notes inbox. It can preserve pass context, request focused proof, or point to scoped v007 repair work without approving v006 by itself.",
        "",
        *command_block(commands["runProducerGradeNotesInbox"]),
        "",
        "Open the post-review action queue. This is the one board that gathers all notes inboxes and repair-planner outputs so producer notes, marker notes, speaker-cleanup notes, parameter-sweep notes, and listen-priority notes do not get stranded in separate reports.",
        "",
        *command_block(commands["openPostReviewActionQueue"]),
        "",
        "Open the repair/tuning console. This is the symptom router: Homer too low, Charlie echo, park noise, robotic gating, restoration artifacts, structural gaps, bad sync, and premature branch rendering all point to the owning stage and the safest next move.",
        "",
        *command_block(commands["openRepairTuningConsole"]),
        "",
        "Open the parameter control ledger. This names the actual tunable audio controls, legal ranges, risks, and proof requirements so repairs do not become mystery-knob folklore.",
        "",
        *command_block(commands["openParameterControlLedger"]),
        "",
        "Open the parameter sweep proof plan. This translates risky knobs into conservative, standard, and aggressive proof-only recipes before any full baseline repair is attempted.",
        "",
        *command_block(commands["openParameterSweepProofPlan"]),
        "",
        "Open the parameter sweep proof snippets. These are short, derived A/B snippets for the sweep variants that can be auditioned honestly from existing proof-pack stems. Unsafe or unavailable routes stay marked as unavailable instead of being faked.",
        "",
        *command_block(commands["openParameterSweepProofSnippetPack"]),
        "",
        "If you export notes from the parameter sweep proof snippets, route them through the parameter-sweep notes inbox. It can name a winning proof variant or request more focused proof without approving v006 or unlocking branches.",
        "",
        *command_block(commands["runParameterSweepNotesInbox"]),
        "",
        "Open the listen-priority console. This is the shortest path through the review: it starts with the riskiest known moments, gives you jump buttons, and exports local notes without changing approval truth.",
        "",
        *command_block(commands["openListenPriorityConsole"]),
        "",
        "Open the human listen control room. This puts the review reel, source-balance A/B proof snippets, and exportable notes on one local page. Use it when you want the least context switching.",
        "",
        *command_block(commands["openHumanListenControlRoom"]),
        "",
        "Open the human listen decision brief. This is the calm producer checklist: what needs to be listened to, what counts as pass/fail/needs-proof, and where the source-balance A/B snippets live.",
        "",
        *command_block(commands["openHumanListenDecisionBrief"]),
        "",
        "Open the human-listen decision rehearsal. This proves the approve/fail/needs-proof commands still dry-run cleanly and that v006 stays locked until an explicit human decision is recorded.",
        "",
        *command_block(commands["openHumanListenDecisionRehearsal"]),
        "",
        "Open the listen-priority snippet pack. This gives short audio clips around the same high-risk windows so nobody has to scrub the full two-hour master just to verify the danger points.",
        "",
        *command_block(commands["openListenPrioritySnippetPack"]),
        "",
        "Open the one-play listen-priority review reel. This stitches the same high-risk snippets into a single M4A with chapter jumps, which is the easiest first listen when you want to know whether v006 sounds human.",
        "",
        *command_block(commands["openListenPriorityReviewReel"]),
        "",
        "Open the source-balance listen companion. This explains the master/source balance warnings in plain language: what the machine saw, what to listen for, and whether pass, needs-proof, or needs-repair is the safer reviewer note.",
        "",
        *command_block(commands["openSourceBalanceListenCompanion"]),
        "",
        "Open the speaker contribution ledger. This is the full-length X-ray for Charlie, Homer, and reference retention: active windows, retained windows, loss-risk spans, bleed-risk spans, and the ranked marker CSV for human/agent review.",
        "",
        *command_block(commands["openSpeakerContributionLedger"]),
        "",
        "Open the speaker preservation proof pack. This turns the contribution ledger's highest-risk Charlie/Homer moments into short source-vs-master A/B proof clips, so reviewers can judge whether the voice was preserved without scrubbing the full two-hour master.",
        "",
        *command_block(commands["openSpeakerPreservationProofPack"]),
        "",
        "If you export notes from the speaker preservation proof pack, route them through the preservation notes inbox. Pass notes become context for this proof slice; needs-proof and needs-repair notes go to the post-review action queue without approving the whole spine.",
        "",
        *command_block(commands["runSpeakerPreservationNotesInbox"]),
        "",
        "Open the speaker activity review board. This explains the speaker-aware cleanup controls: where Charlie/Homer were retained, gated, ducked, or suspicious, and what to listen for before approving the spine.",
        "",
        *command_block(commands["openSpeakerActivityReviewBoard"]),
        "",
        "Open the speaker cleanup proof pack. This gives per-window A/B audio controls for the mastered spine, raw aligned sources, and gated contributions so over-gating, echo, and park-noise cleanup can be judged quickly.",
        "",
        *command_block(commands["openSpeakerCleanupProofPack"]),
        "",
        "Open the speaker cleanup proof pack audit. This verifies that every A/B proof snippet exists, is playable, has sane duration, and keeps approval/branch truth locked before a reviewer trusts the pack.",
        "",
        *command_block(commands["openSpeakerCleanupProofPackAudit"]),
        "",
        "Open the speaker cleanup listen map. This is the compact reviewer decision guide for the same 15 windows: what to listen for, what pass/fail means, and how to route scoped repair notes without mutating v006.",
        "",
        *command_block(commands["openSpeakerCleanupListenMap"]),
        "",
        "Open the speaker cleanup decision matrix. This joins the same cleanup windows with A/B snippets, contribution markers, preservation proof, pass/fail bars, and safe repair actions in one table.",
        "",
        *command_block(commands["openSpeakerCleanupDecisionMatrix"]),
        "",
        "Open the audio spine listen sanity check. This confirms the machine evidence still shows Charlie and Homer materially audible in the mastered spine before human listen approval.",
        "",
        *command_block(commands["openAudioSpineListenSanity"]),
        "",
        "Open the reusable audio production profile. This captures the Episode 4 workbench as a starting preset for future noisy/outdoor Homer recordings without pretending v006 has passed human listen.",
        "",
        *command_block(commands["openReusableAudioProductionProfile"]),
        "",
        "Open the reusable audio production profile smoke. This proves the exported profile can run against a fresh synthetic noisy/outdoor fixture without Episode-4-specific paths, while still requiring real future-episode listen proof before production use.",
        "",
        *command_block(commands["openReusableAudioProductionProfileSmoke"]),
        "",
        "Open the dxRevive manual bounce packet. This is the safe restoration bridge: derived stems only, expected return filenames, and validation before any returned file can affect a candidate.",
        "",
        *command_block(commands["openDxReviveBouncePacket"]),
        "",
        "Open the dxRevive return workbench. This is the one place that shows expected return filenames, missing bounces, validator state, proof-planner state, and the safest next restoration action.",
        "",
        *command_block(commands["openDxReviveReturnWorkbench"]),
        "",
        "Open the latest dxRevive bounce validation. If no returned bounces exist yet, it should say waiting-for-bounces rather than silently pretending restoration happened.",
        "",
        *command_block(commands["openDxReviveBounceValidation"]),
        "",
        "Open the dxRevive bounce validator smoke. This proves the validator rejects missing, duration-mismatched, sample-rate-mismatched, and channel-mismatched returns before real bounces can influence a candidate.",
        "",
        *command_block(commands["openDxReviveBounceValidatorSmoke"]),
        "",
        "Open the dxRevive proof candidate planner. This is the safe bridge from validated returned bounces to A/B proof windows; it should wait honestly until bounces validate.",
        "",
        *command_block(commands["openDxReviveProofCandidatePlanner"]),
        "",
        "Open the dxRevive proof candidate planner smoke. This proves the planner waits, blocks invalid bounces, and renders sandbox A/B proof snippets when the bounce contract is satisfied.",
        "",
        *command_block(commands["openDxReviveProofCandidatePlannerSmoke"]),
        "",
        "Open the source-balance repair workorder if a warning sounds real. It translates each warning family into the smallest safe v007 proof-window move without unlocking branch inheritance.",
        "",
        *command_block(commands["openSourceBalanceRepairWorkorder"]),
        "",
        "Open the source-balance repair preflight if you need exact proof-window render commands. It prepares current-v006 and candidate snippets but keeps rendering locked unless a failed listen or explicit proof-only override exists.",
        "",
        *command_block(commands["openSourceBalanceRepairPreflight"]),
        "",
        "Open the source-balance proof comparison playlist/audit if proof snippets have been rendered. This is the current-v006 vs candidate A/B path for deciding whether a warning needs repair.",
        "",
        *command_block(commands["openSourceBalanceProofComparison"]),
        "",
        "Open the visual overview. Use the full waveform and proof-window cards to orient yourself before listening closely.",
        "",
        *command_block(commands["openVisualOverview"]),
        "",
        "Open the marker review console. Listen at the jump markers, mark pass or needs repair, and export notes JSON.",
        "",
        *command_block(commands["openMarkerConsole"]),
        "",
        "Check current review status at any time:",
        "",
        *command_block(commands["checkStatus"]),
        "",
        "If you prefer a broader cockpit, open the audio review cockpit:",
        "",
        *command_block(commands["openReviewCockpit"]),
        "",
        "## After exporting notes",
        "",
        "Run the post-human-listen notes roundtrip. This is the safest default after using the listen-priority console, human-listen control room, or marker console: it runs the inboxes, repair planner, status board, gate audit, outcome router, START_HERE refresh, and handoff refresh without approving, failing, rendering, or touching source media.",
        "",
        *command_block(commands["runPostHumanListenNotesRoundtrip"]),
        "",
        "Run the post-review action queue if you want the shortest answer to \"what did all those notes mean?\" It gathers every current inbox into repair, focused-proof, pass/context, and waiting-for-notes buckets.",
        "",
        *command_block(commands["runPostReviewActionQueue"]),
        "",
        "Run the listen-priority inbox first. It finds exported notes from the listen-priority console in common locations, validates the baseline, dry-runs the guarded decision command shape, and prints the next safe command.",
        "",
        *command_block(commands["runListenPriorityNotesInbox"]),
        "",
        "If the marker console was used instead, run the marker-review inbox:",
        "",
        *command_block(commands["runMarkerNotesInbox"]),
        "",
        "If the speaker cleanup listen map was used, run its inbox too. All-pass here clears only the focused speaker-cleanup review slice; it does not approve the whole audio spine.",
        "",
        *command_block(commands["runSpeakerCleanupListenMapNotesInbox"]),
        "",
        "If exported notes indicate repair or focused proof, run the repair planner. It converts review notes into scoped v007/focused-proof actions without approving, failing, rendering, or touching source media.",
        "",
        *command_block(commands["runListenNotesRepairPlanner"]),
        "",
        "## Important artifacts",
        "",
        file_line("Listening M4A", paths.get("masterM4a")),
        file_line("Handoff WAV", paths.get("masterWav")),
        file_line("Audio producer command center", paths.get("producerCommandCenter")),
        file_line("Audio producer command center HTML", paths.get("producerCommandCenterHtml")),
        file_line("Audio producer command center open command", paths.get("producerCommandCenterOpenCommand")),
        file_line("Audio runway state", paths.get("audioRunwayState")),
        file_line("Audio runway state HTML", paths.get("audioRunwayStateHtml")),
        file_line("Audio runway state open command", paths.get("audioRunwayStateOpenCommand")),
        file_line("Listen proof coverage map", paths.get("listenProofCoverageMap")),
        file_line("Listen proof coverage map HTML", paths.get("listenProofCoverageMapHtml")),
        file_line("Listen proof coverage map open command", paths.get("listenProofCoverageMapOpenCommand")),
        file_line("Human listen decision front door", paths.get("humanListenDecisionFrontDoor")),
        file_line("Human listen decision front door HTML", paths.get("humanListenDecisionFrontDoorHtml")),
        file_line("Human listen decision front door open command", paths.get("humanListenDecisionFrontDoorOpenCommand")),
        file_line("Human listen decision front-door smoke", paths.get("humanListenDecisionFrontDoorSmoke")),
        file_line("Post-listen outcome router", paths.get("postListenOutcomeRouter")),
        file_line("Post-listen outcome router HTML", paths.get("postListenOutcomeRouterHtml")),
        file_line("Post-listen outcome router open command", paths.get("postListenOutcomeRouterOpenCommand")),
        file_line("Reviewer notes template", paths.get("reviewerNotesTemplate")),
        file_line("Reviewer notes template HTML", paths.get("reviewerNotesTemplateHtml")),
        file_line("Reviewer notes template open command", paths.get("reviewerNotesTemplateOpenCommand")),
        file_line("Branch inheritance gate", paths.get("branchInheritanceGate")),
        file_line("Branch inheritance gate HTML", paths.get("branchInheritanceGateHtml")),
        file_line("Branch inheritance gate open command", paths.get("branchInheritanceGateOpenCommand")),
        file_line("Branch render preflight", paths.get("branchRenderPreflight")),
        file_line("Branch render preflight HTML", paths.get("branchRenderPreflightHtml")),
        file_line("Branch render preflight open command", paths.get("branchRenderPreflightOpenCommand")),
        file_line("Approval-path sandbox smoke", paths.get("approvalPathSmoke")),
        file_line("Approval-path sandbox smoke open command", paths.get("approvalPathSmokeOpenCommand")),
        file_line("Unresolved requirement review", paths.get("unresolvedRequirementReview")),
        file_line("Unresolved requirement review HTML", paths.get("unresolvedRequirementReviewHtml")),
        file_line("Unresolved requirement review open command", paths.get("unresolvedRequirementReviewOpenCommand")),
        file_line("Audio production doctrine", paths.get("audioProductionDoctrine")),
        file_line("Audio production doctrine HTML", paths.get("audioProductionDoctrineHtml")),
        file_line("Audio production doctrine open command", paths.get("audioProductionDoctrineOpenCommand")),
        file_line("Audio transformation lineage ledger", paths.get("audioTransformationLineageLedger")),
        file_line("Audio transformation lineage ledger HTML", paths.get("audioTransformationLineageLedgerHtml")),
        file_line("Audio transformation lineage ledger open command", paths.get("audioTransformationLineageLedgerOpenCommand")),
        file_line("Audio transformation lineage ledger smoke", paths.get("audioTransformationLineageLedgerSmoke")),
        file_line("Audio transformation lineage ledger smoke open command", paths.get("audioTransformationLineageLedgerSmokeOpenCommand")),
        file_line("Audio workbench stage control surface", paths.get("stageControlSurface")),
        file_line("Audio workbench stage control surface HTML", paths.get("stageControlSurfaceHtml")),
        file_line("Audio producer-grade audit", paths.get("producerGradeAudit")),
        file_line("Audio producer-grade audit HTML", paths.get("producerGradeAuditHtml")),
        file_line("Audio producer-grade notes template", paths.get("producerGradeNotesTemplate")),
        file_line("Audio producer-grade notes inbox", paths.get("producerGradeNotesInbox")),
        file_line("Audio producer-grade notes inbox smoke", paths.get("producerGradeNotesInboxSmoke")),
        file_line("Audio producer-grade audit smoke", paths.get("producerGradeAuditSmoke")),
        file_line("Audio post-review action queue", paths.get("postReviewActionQueue")),
        file_line("Audio repair/tuning console", paths.get("repairTuningConsole")),
        file_line("Audio repair/tuning console HTML", paths.get("repairTuningConsoleHtml")),
        file_line("Audio parameter control ledger", paths.get("parameterControlLedger")),
        file_line("Audio parameter control ledger HTML", paths.get("parameterControlLedgerHtml")),
        file_line("Audio parameter sweep proof plan", paths.get("parameterSweepProofPlan")),
        file_line("Audio parameter sweep proof plan HTML", paths.get("parameterSweepProofPlanHtml")),
        file_line("Audio parameter sweep proof snippet pack", paths.get("parameterSweepProofSnippetPack")),
        file_line("Audio parameter sweep proof snippet pack HTML", paths.get("parameterSweepProofSnippetPackHtml")),
        file_line("Audio parameter sweep proof snippet playlist", paths.get("parameterSweepProofSnippetPackPlaylist")),
        file_line("Audio parameter sweep proof snippet smoke", paths.get("parameterSweepProofSnippetPackSmoke")),
        file_line("Audio parameter sweep proof notes inbox", paths.get("parameterSweepNotesInbox")),
        file_line("Audio parameter sweep proof notes inbox smoke", paths.get("parameterSweepNotesInboxSmoke")),
        file_line("Audio listen-priority console", paths.get("listenPriorityConsole")),
        file_line("Audio listen-priority queue", paths.get("listenPriorityQueue")),
        file_line("Audio listen-priority snippet pack", paths.get("listenPrioritySnippetPack")),
        file_line("Audio listen-priority snippet pack HTML", paths.get("listenPrioritySnippetPackHtml")),
        file_line("Audio listen-priority snippet playlist", paths.get("listenPrioritySnippetPackPlaylist")),
        file_line("Audio listen-priority review reel", paths.get("listenPriorityReviewReel")),
        file_line("Audio listen-priority review reel HTML", paths.get("listenPriorityReviewReelHtml")),
        file_line("Audio listen-priority review reel M4A", paths.get("listenPriorityReviewReelM4a")),
        file_line("Audio listen-priority review reel notes template", paths.get("listenPriorityReviewReelNotesTemplate")),
        file_line("Audio listen-priority review reel notes smoke", paths.get("listenPriorityReviewReelNotesSmoke")),
        file_line("Audio listen-priority snippet pack audit", paths.get("listenPrioritySnippetPackAudit")),
        file_line("Audio final-listen fast pass", paths.get("finalListenFastPass")),
        file_line("Audio final-listen fast pass HTML", paths.get("finalListenFastPassHtml")),
        file_line("Audio final-listen fast pass notes template", paths.get("finalListenFastPassNotesTemplate")),
        file_line("Audio final-listen fast pass notes inbox", paths.get("finalListenFastPassNotesInbox")),
        file_line("Audio platform loudness audit", paths.get("platformLoudnessAudit")),
        file_line("Audio platform loudness audit HTML", paths.get("platformLoudnessAuditHtml")),
        file_line("Audio broadcast polish scorecard", paths.get("broadcastPolishScorecard")),
        file_line("Audio broadcast polish scorecard HTML", paths.get("broadcastPolishScorecardHtml")),
        file_line("Audio technical audition snippet pack", paths.get("technicalAuditionSnippetPack")),
        file_line("Audio technical audition snippet pack HTML", paths.get("technicalAuditionSnippetPackHtml")),
        file_line("Audio technical audition snippet notes template", paths.get("technicalAuditionSnippetPackNotesTemplate")),
        file_line("Audio technical audition notes inbox", paths.get("technicalAuditionNotesInbox")),
        file_line("Audio smoothness proof pack", paths.get("smoothnessProofPack")),
        file_line("Audio smoothness proof pack HTML", paths.get("smoothnessProofPackHtml")),
        file_line("Audio smoothness proof pack playlist", paths.get("smoothnessProofPackPlaylist")),
        file_line("Audio smoothness proof notes template", paths.get("smoothnessProofPackNotesTemplate")),
        file_line("Audio smoothness proof notes inbox", paths.get("smoothnessProofNotesInbox")),
        file_line("Audio human listen control room", paths.get("humanListenControlRoom")),
        file_line("Audio human listen decision brief", paths.get("humanListenDecisionBrief")),
        file_line("Human-listen decision rehearsal", paths.get("humanListenDecisionRehearsal")),
        file_line("Audio source-balance listen companion", paths.get("sourceBalanceListenCompanion")),
        file_line("Audio source-balance listen companion open command", paths.get("sourceBalanceListenCompanionOpenCommand")),
        file_line("Audio speaker contribution ledger", paths.get("speakerContributionLedger")),
        file_line("Audio speaker contribution ledger HTML", paths.get("speakerContributionLedgerHtml")),
        file_line("Audio speaker contribution review markers CSV", paths.get("speakerContributionLedgerCsv")),
        file_line("Audio speaker preservation proof pack", paths.get("speakerPreservationProofPack")),
        file_line("Audio speaker preservation proof pack HTML", paths.get("speakerPreservationProofPackHtml")),
        file_line("Audio speaker preservation proof pack playlist", paths.get("speakerPreservationProofPackPlaylist")),
        file_line("Audio speaker preservation proof notes template", paths.get("speakerPreservationProofNotesTemplate")),
        file_line("Audio speaker preservation proof notes inbox", paths.get("speakerPreservationProofNotesInbox")),
        file_line("Audio speaker activity review board", paths.get("speakerActivityReviewBoard")),
        file_line("Audio speaker activity review board HTML", paths.get("speakerActivityReviewBoardHtml")),
        file_line("Audio speaker cleanup proof pack", paths.get("speakerCleanupProofPack")),
        file_line("Audio speaker cleanup proof pack HTML", paths.get("speakerCleanupProofPackHtml")),
        file_line("Audio speaker cleanup proof pack audit", paths.get("speakerCleanupProofPackAudit")),
        file_line("Audio speaker cleanup listen map", paths.get("speakerCleanupListenMap")),
        file_line("Audio speaker cleanup listen map HTML", paths.get("speakerCleanupListenMapHtml")),
        file_line("Audio spine listen sanity check", paths.get("audioSpineListenSanity")),
        file_line("Reusable audio production profile", paths.get("reusableAudioProductionProfile")),
        file_line("Stable reusable audio production profile", paths.get("stableReusableAudioProductionProfile")),
        file_line("Reusable audio production profile smoke", paths.get("reusableAudioProductionProfileSmoke")),
        file_line("dxRevive manual bounce packet", paths.get("dxReviveManualBouncePacket")),
        file_line("dxRevive manual bounce packet open command", paths.get("dxReviveManualBouncePacketOpenCommand")),
        file_line("dxRevive return workbench", paths.get("dxReviveReturnWorkbench")),
        file_line("dxRevive return workbench HTML", paths.get("dxReviveReturnWorkbenchHtml")),
        file_line("dxRevive return workbench open command", paths.get("dxReviveReturnWorkbenchOpenCommand")),
        file_line("dxRevive bounce validation", paths.get("dxReviveBounceValidation")),
        file_line("dxRevive bounce validator smoke", paths.get("dxReviveBounceValidatorSmoke")),
        file_line("dxRevive proof candidate planner", paths.get("dxReviveProofCandidatePlanner")),
        file_line("dxRevive proof candidate planner smoke", paths.get("dxReviveProofCandidatePlannerSmoke")),
        file_line("Audio source-balance repair workorder", paths.get("sourceBalanceRepairWorkorder")),
        file_line("Audio source-balance repair preflight", paths.get("sourceBalanceRepairPreflight")),
        file_line("Audio source-balance repair preflight audit", paths.get("sourceBalanceRepairPreflightAudit")),
        file_line("Audio source-balance repair proof playlist", paths.get("sourceBalanceRepairProofPlaylist")),
        file_line("Audio listen-priority notes inbox", paths.get("listenPriorityNotesInbox")),
        file_line("Speaker cleanup listen-map notes inbox", paths.get("speakerCleanupListenMapNotesInbox")),
        file_line("Speaker cleanup listen-map notes inbox smoke", paths.get("speakerCleanupListenMapNotesInboxSmoke")),
        file_line("Speaker preservation proof notes inbox", paths.get("speakerPreservationProofNotesInbox")),
        file_line("Audio listen-notes repair planner", paths.get("listenNotesRepairPlanner")),
        file_line("Audio post-human-listen notes roundtrip", paths.get("postHumanListenNotesRoundtrip")),
        file_line("Audio post-human-listen notes roundtrip smoke", paths.get("postHumanListenNotesRoundtripSmoke")),
        file_line("Audio post-human-listen notes roundtrip command", paths.get("postHumanListenNotesRoundtripCommand")),
        file_line("Audio master visual overview", paths.get("visualOverview")),
        file_line("Audio master visual overview HTML", paths.get("visualOverviewHtml")),
        file_line("Audio master full waveform", paths.get("visualOverviewWaveform")),
        file_line("Audio master/source balance audit", paths.get("masterSourceBalanceAudit")),
        file_line("Speaker bleed/gap proof audit", paths.get("speakerBleedGapProofAudit")),
        file_line("Audio goal completion audit", paths.get("goalCompletionAudit")),
        file_line("Stable status board", paths.get("statusBoard")),
        file_line("Status check command", paths.get("statusCheckCommand")),
        file_line("Marker review console", paths.get("markerReviewConsole")),
        file_line("Marker review notes inbox", paths.get("markerReviewNotesInbox")),
        file_line("Marker review notes inbox smoke", paths.get("markerReviewNotesInboxSmoke")),
        file_line("Marker command packet", paths.get("markerCommandPacket")),
        file_line("Latest handoff index", paths.get("handoffIndex")),
        file_line("Latest readiness verification", paths.get("readinessVerification")),
        "",
        "## If the listen passes",
        "",
        "Do not hand-edit the manifest. Use the guarded bridge command produced by the inbox or command packet. It requires explicit human-listen confirmation.",
        "",
        "## If the listen fails",
        "",
        "Record the failure through the same guarded bridge, then make a v007 or timestamped repair candidate. Do not overwrite v006.",
        "",
        "## Guardrail",
        "",
        "Quipsly can make the review path calm and obvious. It cannot pretend someone listened. Branch rendering stays locked until a real human listen decision is recorded.",
        "",
    ]
    return "\n".join(lines)


def build_open_command(report: dict[str, Any]) -> str:
    commands = report["commands"]
    lines = [
        "#!/bin/zsh",
        "set -euo pipefail",
        "",
        "echo 'Opening Quipsly Episode 4 audio review...'",
        "echo 'Opening producer command center...'",
        *commands["openProducerCommandCenter"],
        "",
        "echo 'Opening human approval preflight...'",
        *commands["openHumanApprovalPreflight"],
        "",
        "echo 'Opening post-listen outcome router...'",
        *commands["openPostListenOutcomeRouter"],
        "",
        "echo 'Opening unresolved requirement review...'",
        *commands["openUnresolvedRequirementReview"],
        "",
        "echo 'Opening audio production doctrine...'",
        *commands["openAudioProductionDoctrine"],
        "",
        "echo 'Opening audio transformation lineage ledger...'",
        *commands["openAudioTransformationLineageLedger"],
        "",
        "echo 'Opening audio transformation lineage ledger smoke...'",
        *commands["openAudioTransformationLineageLedgerSmoke"],
        "",
        "echo 'Opening audio workbench stage control surface...'",
        *commands["openStageControlSurface"],
        "",
        "echo 'Opening final-listen fast pass...'",
        *commands["openFinalListenFastPass"],
        "",
        "echo 'Opening broadcast polish scorecard...'",
        *commands["openBroadcastPolishScorecard"],
        "",
        "echo 'Opening smoothness proof pack...'",
        *commands["openSmoothnessProofPack"],
        "",
        "echo 'Opening producer-grade audio audit...'",
        *commands["openProducerGradeAudit"],
        "",
        "echo 'Opening post-review action queue...'",
        *commands["openPostReviewActionQueue"],
        "",
        "echo 'Opening listen-priority console...'",
        *commands["openListenPriorityConsole"],
        "",
        "echo 'Opening parameter sweep proof snippets...'",
        *commands["openParameterSweepProofSnippetPack"],
        "",
        "echo 'Opening listen-priority snippet pack...'",
        *commands["openListenPrioritySnippetPack"],
        "",
        "echo 'Opening listen-priority review reel...'",
        *commands["openListenPriorityReviewReel"],
        "",
        "echo 'Opening source-balance listen companion...'",
        *commands["openSourceBalanceListenCompanion"],
        "",
        "echo 'Opening audio master visual overview...'",
        *commands["openVisualOverview"],
        "",
        "echo 'Opening marker review console...'",
        *commands["openMarkerConsole"],
        "",
        "echo 'Opening START_HERE markdown...'",
        f"open {shell_quote(report['markdownPath'])}",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline-dir", required=True, type=Path)
    args = parser.parse_args()

    baseline_dir = resolve_baseline_dir(args.baseline_dir)
    manifest_path = baseline_dir / "manifest.json"
    manifest = read_json(manifest_path)
    outputs = manifest.setdefault("outputs", {})
    baseline_id = str(manifest.get("baselineId") or "audio-baseline")
    generated_at = datetime.now(timezone.utc).isoformat()

    paths = {
        "masterM4a": output_path(outputs.get("masterM4a")),
        "masterWav": output_path(outputs.get("masterWav")),
        "producerCommandCenter": output_path(outputs.get("latestAudioProducerCommandCenterMarkdown")),
        "producerCommandCenterHtml": output_path(outputs.get("latestAudioProducerCommandCenterHtml")),
        "producerCommandCenterJson": output_path(outputs.get("latestAudioProducerCommandCenter")),
        "producerCommandCenterOpenCommand": output_path(outputs.get("latestAudioProducerCommandCenterOpenCommand")),
        "audioRunwayState": output_path(outputs.get("latestAudioRunwayStateMarkdown")),
        "audioRunwayStateHtml": output_path(outputs.get("latestAudioRunwayStateHtml")),
        "audioRunwayStateJson": output_path(outputs.get("latestAudioRunwayState")),
        "audioRunwayStateOpenCommand": output_path(outputs.get("latestAudioRunwayStateOpenCommand")),
        "listenProofCoverageMap": output_path(outputs.get("latestAudioListenProofCoverageMapMarkdown")),
        "listenProofCoverageMapHtml": output_path(outputs.get("latestAudioListenProofCoverageMapHtml")),
        "listenProofCoverageMapJson": output_path(outputs.get("latestAudioListenProofCoverageMap")),
        "listenProofCoverageMapOpenCommand": output_path(outputs.get("latestAudioListenProofCoverageMapOpenCommand")),
        "humanApprovalPreflight": output_path(outputs.get("latestAudioHumanApprovalPreflightMarkdown")),
        "humanApprovalPreflightHtml": output_path(outputs.get("latestAudioHumanApprovalPreflightHtml")),
        "humanApprovalPreflightJson": output_path(outputs.get("latestAudioHumanApprovalPreflightJson")),
        "humanApprovalPreflightOpenCommand": output_path(outputs.get("latestAudioHumanApprovalPreflightOpenCommand")),
        "humanListenDecisionFrontDoor": output_path(outputs.get("latestHumanListenDecisionFrontDoorMarkdown")),
        "humanListenDecisionFrontDoorHtml": output_path(outputs.get("latestHumanListenDecisionFrontDoorHtml")),
        "humanListenDecisionFrontDoorJson": output_path(outputs.get("latestHumanListenDecisionFrontDoor")),
        "humanListenDecisionFrontDoorOpenCommand": output_path(outputs.get("latestHumanListenDecisionFrontDoorOpenCommand")),
        "humanListenDecisionFrontDoorSmoke": output_path(outputs.get("latestHumanListenDecisionFrontDoorSmokeMarkdown")),
        "postListenOutcomeRouter": output_path(outputs.get("latestAudioPostListenOutcomeRouterMarkdown")) or output_path(outputs.get("latestPostListenOutcomeRouterMarkdown")),
        "postListenOutcomeRouterHtml": output_path(outputs.get("latestAudioPostListenOutcomeRouterStableHtml")) or output_path(outputs.get("latestAudioPostListenOutcomeRouterHtml")) or output_path(outputs.get("latestPostListenOutcomeRouterHtml")),
        "postListenOutcomeRouterOpenCommand": output_path(outputs.get("latestAudioPostListenOutcomeRouterOpenCommand")) or output_path(outputs.get("latestPostListenOutcomeRouterOpenCommand")),
        "reviewerNotesTemplate": output_path(outputs.get("latestReviewerNotesTemplateMarkdown")),
        "reviewerNotesTemplateHtml": output_path(outputs.get("latestReviewerNotesTemplateHtml")),
        "reviewerNotesTemplateJson": output_path(outputs.get("latestReviewerNotesTemplate")),
        "reviewerNotesTemplateOpenCommand": output_path(outputs.get("latestReviewerNotesTemplateOpenCommand")),
        "branchInheritanceGate": output_path(outputs.get("latestBranchInheritanceGateMarkdown")),
        "branchInheritanceGateHtml": output_path(outputs.get("latestBranchInheritanceGateHtml")),
        "branchInheritanceGateJson": output_path(outputs.get("latestBranchInheritanceGate")),
        "branchInheritanceGateOpenCommand": output_path(outputs.get("latestBranchInheritanceGateOpenCommand")),
        "branchRenderPreflight": output_path(outputs.get("branchRenderPreflightMarkdown")),
        "branchRenderPreflightHtml": output_path(outputs.get("branchRenderPreflightHtml")),
        "branchRenderPreflightJson": output_path(outputs.get("branchRenderPreflight")),
        "branchRenderPreflightOpenCommand": output_path(outputs.get("branchRenderPreflightOpenCommand")),
        "approvalPathSmoke": output_path(outputs.get("latestApprovalPathSmokeMarkdown")),
        "approvalPathSmokeJson": output_path(outputs.get("latestApprovalPathSmoke")),
        "approvalPathSmokeOpenCommand": output_path(outputs.get("latestApprovalPathSmokeOpenCommand")),
        "unresolvedRequirementReview": output_path(outputs.get("latestAudioUnresolvedRequirementReviewMarkdown")),
        "unresolvedRequirementReviewHtml": output_path(outputs.get("latestAudioUnresolvedRequirementReviewHtml")),
        "unresolvedRequirementReviewJson": output_path(outputs.get("latestAudioUnresolvedRequirementReview")),
        "unresolvedRequirementReviewOpenCommand": output_path(outputs.get("latestAudioUnresolvedRequirementReviewOpenCommand")),
        "audioProductionDoctrine": output_path(outputs.get("latestAudioProductionDoctrineMarkdown")),
        "audioProductionDoctrineHtml": output_path(outputs.get("latestAudioProductionDoctrineHtml")),
        "audioProductionDoctrineJson": output_path(outputs.get("latestAudioProductionDoctrine")),
        "audioProductionDoctrineOpenCommand": output_path(outputs.get("latestAudioProductionDoctrineOpenCommand")),
        "audioTransformationLineageLedger": output_path(outputs.get("latestAudioTransformationLineageLedgerMarkdown")),
        "audioTransformationLineageLedgerHtml": output_path(outputs.get("latestAudioTransformationLineageLedgerHtml")),
        "audioTransformationLineageLedgerJson": output_path(outputs.get("latestAudioTransformationLineageLedger")),
        "audioTransformationLineageLedgerOpenCommand": output_path(outputs.get("latestAudioTransformationLineageLedgerOpenCommand")),
        "audioTransformationLineageLedgerSmoke": output_path(outputs.get("latestAudioTransformationLineageLedgerSmokeMarkdown")),
        "audioTransformationLineageLedgerSmokeJson": output_path(outputs.get("latestAudioTransformationLineageLedgerSmoke")),
        "audioTransformationLineageLedgerSmokeOpenCommand": output_path(outputs.get("latestAudioTransformationLineageLedgerSmokeOpenCommand")),
        "statusBoard": output_path(outputs.get("latestAudioReviewStatusBoardStableMarkdown")),
        "statusCheckCommand": output_path(outputs.get("latestAudioReviewStatusCheckCommand")),
        "markerReviewConsole": output_path(outputs.get("latestEditorMarkerReviewConsoleHtml")),
        "reviewCockpit": output_path(outputs.get("audioReviewCockpitHtml")),
        "stageControlSurface": output_path(outputs.get("latestAudioWorkbenchStageControlSurfaceMarkdown")),
        "stageControlSurfaceHtml": output_path(outputs.get("latestAudioWorkbenchStageControlSurfaceHtml")),
        "stageControlSurfaceOpenCommand": output_path(outputs.get("latestAudioWorkbenchStageControlSurfaceOpenCommand")),
        "producerGradeAudit": output_path(outputs.get("latestAudioProducerGradeAuditMarkdown")),
        "producerGradeAuditHtml": output_path(outputs.get("latestAudioProducerGradeAuditHtml")),
        "producerGradeAuditOpenCommand": output_path(outputs.get("latestAudioProducerGradeAuditOpenCommand")),
        "producerGradeNotesTemplate": output_path(outputs.get("latestAudioProducerGradeNotesTemplate")),
        "producerGradeNotesInbox": output_path(outputs.get("latestAudioProducerGradeNotesInboxMarkdown")),
        "producerGradeNotesInboxSmoke": output_path(outputs.get("latestAudioProducerGradeNotesInboxSmokeMarkdown")),
        "producerGradeAuditSmoke": output_path(outputs.get("latestAudioProducerGradeAuditSmokeMarkdown")),
        "postReviewActionQueue": output_path(outputs.get("latestAudioPostReviewActionQueueMarkdown")),
        "repairTuningConsole": output_path(outputs.get("latestAudioWorkbenchRepairTuningConsoleMarkdown")),
        "repairTuningConsoleHtml": output_path(outputs.get("latestAudioWorkbenchRepairTuningConsoleHtml")),
        "repairTuningConsoleOpenCommand": output_path(outputs.get("latestAudioWorkbenchRepairTuningConsoleOpenCommand")),
        "parameterControlLedger": output_path(outputs.get("latestAudioWorkbenchParameterControlLedgerMarkdown")),
        "parameterControlLedgerHtml": output_path(outputs.get("latestAudioWorkbenchParameterControlLedgerHtml")),
        "parameterControlLedgerOpenCommand": output_path(outputs.get("latestAudioWorkbenchParameterControlLedgerOpenCommand")),
        "parameterSweepProofPlan": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofPlanMarkdown")),
        "parameterSweepProofPlanHtml": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofPlanHtml")),
        "parameterSweepProofPlanOpenCommand": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofPlanOpenCommand")),
        "parameterSweepProofSnippetPack": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofSnippetPackMarkdown")),
        "parameterSweepProofSnippetPackHtml": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofSnippetPackHtml")),
        "parameterSweepProofSnippetPackPlaylist": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofSnippetPackPlaylist")),
        "parameterSweepProofSnippetPackOpenCommand": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofSnippetPackOpenCommand")),
        "parameterSweepProofSnippetPackSmoke": output_path(outputs.get("latestAudioWorkbenchParameterSweepProofSnippetPackSmokeMarkdown")),
        "parameterSweepNotesInbox": output_path(outputs.get("latestAudioWorkbenchParameterSweepNotesInboxMarkdown")),
        "parameterSweepNotesInboxSmoke": output_path(outputs.get("latestAudioWorkbenchParameterSweepNotesInboxSmokeMarkdown")),
        "visualOverview": output_path(outputs.get("latestAudioMasterVisualOverviewMarkdown")),
        "visualOverviewHtml": output_path(outputs.get("latestAudioMasterVisualOverviewHtml")),
        "visualOverviewWaveform": output_path(outputs.get("latestAudioMasterVisualOverviewFullWaveformPng")),
        "masterSourceBalanceAudit": output_path(outputs.get("latestAudioMasterSourceBalanceAuditMarkdown")),
        "speakerBleedGapProofAudit": output_path(outputs.get("latestSpeakerBleedGapProofAuditMarkdown")),
        "goalCompletionAudit": output_path(outputs.get("latestAudioGoalCompletionAuditMarkdown")),
        "listenPriorityConsole": output_path(outputs.get("latestAudioListenPriorityConsoleHtml")),
        "listenPriorityQueue": output_path(outputs.get("latestAudioListenPriorityQueueMarkdown")),
        "listenPrioritySnippetPack": output_path(outputs.get("latestAudioListenPrioritySnippetPackMarkdown")),
        "listenPrioritySnippetPackHtml": output_path(outputs.get("latestAudioListenPrioritySnippetPackHtml")),
        "listenPrioritySnippetPackPlaylist": output_path(outputs.get("latestAudioListenPrioritySnippetPackPlaylist")),
        "listenPrioritySnippetPackOpenCommand": output_path(outputs.get("latestAudioListenPrioritySnippetPackOpenCommand")),
        "listenPriorityReviewReel": output_path(outputs.get("latestAudioListenPriorityReviewReelMarkdown")),
        "listenPriorityReviewReelHtml": output_path(outputs.get("latestAudioListenPriorityReviewReelHtml")),
        "listenPriorityReviewReelOpenCommand": output_path(outputs.get("latestAudioListenPriorityReviewReelOpenCommand")),
        "listenPriorityReviewReelM4a": output_path(outputs.get("latestAudioListenPriorityReviewReelM4a")),
        "listenPriorityReviewReelNotesTemplate": output_path(outputs.get("latestAudioListenPriorityReviewReelNotesTemplate")),
        "listenPriorityReviewReelNotesSmoke": output_path(outputs.get("latestAudioListenPriorityReviewReelNotesSmokeMarkdown")),
        "listenPrioritySnippetPackAudit": output_path(outputs.get("latestAudioListenPrioritySnippetPackAuditMarkdown")),
        "finalListenFastPass": output_path(outputs.get("latestAudioFinalListenFastPassMarkdown")),
        "finalListenFastPassHtml": output_path(outputs.get("latestAudioFinalListenFastPassHtml")),
        "finalListenFastPassOpenCommand": output_path(outputs.get("latestAudioFinalListenFastPassOpenCommand")),
        "finalListenFastPassNotesTemplate": output_path(outputs.get("latestAudioFinalListenFastPassNotesTemplate")),
        "finalListenFastPassNotesInbox": output_path(outputs.get("latestAudioFinalListenFastPassNotesInboxMarkdown")),
        "platformLoudnessAudit": output_path(outputs.get("latestAudioPlatformLoudnessAuditMarkdown")),
        "platformLoudnessAuditHtml": output_path(outputs.get("latestAudioPlatformLoudnessAuditHtml")),
        "platformLoudnessAuditOpenCommand": output_path(outputs.get("latestAudioPlatformLoudnessAuditOpenCommand")),
        "broadcastPolishScorecard": output_path(outputs.get("latestAudioBroadcastPolishScorecardMarkdown")),
        "broadcastPolishScorecardHtml": output_path(outputs.get("latestAudioBroadcastPolishScorecardHtml")),
        "broadcastPolishScorecardOpenCommand": output_path(outputs.get("latestAudioBroadcastPolishScorecardOpenCommand")),
        "technicalAuditionSnippetPack": output_path(outputs.get("latestAudioTechnicalAuditionSnippetPackMarkdown")),
        "technicalAuditionSnippetPackHtml": output_path(outputs.get("latestAudioTechnicalAuditionSnippetPackHtml")),
        "technicalAuditionSnippetPackOpenCommand": output_path(outputs.get("latestAudioTechnicalAuditionSnippetPackOpenCommand")),
        "technicalAuditionSnippetPackNotesTemplate": output_path(outputs.get("latestAudioTechnicalAuditionSnippetPackNotesTemplate")),
        "technicalAuditionNotesInbox": output_path(outputs.get("latestAudioTechnicalAuditionNotesInboxMarkdown")),
        "smoothnessProofPack": output_path(outputs.get("latestAudioSmoothnessProofPackMarkdown")),
        "smoothnessProofPackHtml": output_path(outputs.get("latestAudioSmoothnessProofPackHtml")),
        "smoothnessProofPackPlaylist": output_path(outputs.get("latestAudioSmoothnessProofPackPlaylist")),
        "smoothnessProofPackNotesTemplate": output_path(outputs.get("latestAudioSmoothnessProofPackNotesTemplate")),
        "smoothnessProofPackOpenCommand": output_path(outputs.get("latestAudioSmoothnessProofPackOpenCommand")),
        "smoothnessProofNotesInbox": output_path(outputs.get("latestAudioSmoothnessProofNotesInboxMarkdown")),
        "humanListenControlRoom": output_path(outputs.get("latestAudioHumanListenControlRoomHtml")),
        "humanListenControlRoomMarkdown": output_path(outputs.get("latestAudioHumanListenControlRoomMarkdown")),
        "humanListenControlRoomOpenCommand": output_path(outputs.get("latestAudioHumanListenControlRoomOpenCommand")),
        "humanListenDecisionBrief": output_path(outputs.get("latestAudioHumanListenDecisionBriefMarkdown")),
        "humanListenDecisionRehearsal": output_path(outputs.get("latestHumanListenDecisionRehearsalMarkdown")),
        "humanListenDecisionRehearsalOpenCommand": output_path(outputs.get("latestHumanListenDecisionRehearsalOpenCommand")),
        "sourceBalanceListenCompanion": output_path(outputs.get("latestAudioSourceBalanceListenCompanionMarkdown")),
        "sourceBalanceListenCompanionOpenCommand": output_path(outputs.get("latestAudioSourceBalanceListenCompanionOpenCommand")),
        "speakerContributionLedger": output_path(outputs.get("latestAudioSpeakerContributionLedgerMarkdown")),
        "speakerContributionLedgerHtml": output_path(outputs.get("latestAudioSpeakerContributionLedgerHtml")),
        "speakerContributionLedgerCsv": output_path(outputs.get("latestAudioSpeakerContributionLedgerCsv")),
        "speakerContributionLedgerOpenCommand": output_path(outputs.get("latestAudioSpeakerContributionLedgerOpenCommand")),
        "speakerPreservationProofPack": output_path(outputs.get("latestAudioSpeakerPreservationProofPackMarkdown")),
        "speakerPreservationProofPackHtml": output_path(outputs.get("latestAudioSpeakerPreservationProofPackHtml")),
        "speakerPreservationProofPackPlaylist": output_path(outputs.get("latestAudioSpeakerPreservationProofPackPlaylist")),
        "speakerPreservationProofNotesTemplate": output_path(outputs.get("latestAudioSpeakerPreservationProofPackNotesTemplate")),
        "speakerPreservationProofPackOpenCommand": output_path(outputs.get("latestAudioSpeakerPreservationProofPackOpenCommand")),
        "speakerPreservationProofNotesInbox": output_path(outputs.get("latestAudioSpeakerPreservationProofNotesInboxMarkdown")),
        "speakerActivityReviewBoard": output_path(outputs.get("latestAudioSpeakerActivityReviewBoardMarkdown")),
        "speakerActivityReviewBoardHtml": output_path(outputs.get("latestAudioSpeakerActivityReviewBoardHtml")),
        "speakerCleanupProofPack": output_path(outputs.get("latestSpeakerCleanupProofPackMarkdown")),
        "speakerCleanupProofPackHtml": output_path(outputs.get("latestSpeakerCleanupProofPackHtml")),
        "speakerCleanupProofPackAudit": output_path(outputs.get("latestSpeakerCleanupProofPackAuditMarkdown")),
        "speakerCleanupListenMap": output_path(outputs.get("latestSpeakerCleanupListenMapMarkdown")),
        "speakerCleanupListenMapHtml": output_path(outputs.get("latestSpeakerCleanupListenMapHtml")),
        "speakerCleanupListenMapOpenCommand": output_path(outputs.get("latestSpeakerCleanupListenMapOpenCommand")),
        "speakerCleanupDecisionMatrix": output_path(outputs.get("latestSpeakerCleanupDecisionMatrixMarkdown")),
        "speakerCleanupDecisionMatrixHtml": output_path(outputs.get("latestSpeakerCleanupDecisionMatrixHtml")),
        "speakerCleanupDecisionMatrixOpenCommand": output_path(outputs.get("latestSpeakerCleanupDecisionMatrixOpenCommand")),
        "audioSpineListenSanity": output_path(outputs.get("latestAudioSpineListenSanityCheckMarkdown")),
        "reusableAudioProductionProfile": output_path(outputs.get("latestReusableAudioProductionProfileMarkdown")),
        "stableReusableAudioProductionProfile": output_path(outputs.get("stableReusableAudioProductionProfileMarkdown")),
        "reusableAudioProductionProfileSmoke": output_path(outputs.get("latestReusableAudioProductionProfileSmokeMarkdown")),
        "dxReviveManualBouncePacket": output_path(outputs.get("latestDxReviveManualBouncePacketMarkdown")),
        "dxReviveManualBouncePacketOpenCommand": output_path(outputs.get("latestDxReviveManualBouncePacketOpenCommand")),
        "dxReviveReturnWorkbench": output_path(outputs.get("latestDxReviveReturnWorkbenchMarkdown")),
        "dxReviveReturnWorkbenchHtml": output_path(outputs.get("latestDxReviveReturnWorkbenchHtml")),
        "dxReviveReturnWorkbenchOpenCommand": output_path(outputs.get("latestDxReviveReturnWorkbenchOpenCommand")),
        "dxReviveBounceValidation": output_path(outputs.get("latestDxReviveBounceValidationMarkdown")),
        "dxReviveBounceValidatorSmoke": output_path(outputs.get("latestDxReviveBounceValidatorSmokeMarkdown")),
        "dxReviveProofCandidatePlanner": output_path(outputs.get("latestDxReviveProofCandidatePlannerMarkdown")),
        "dxReviveProofCandidatePlannerSmoke": output_path(outputs.get("latestDxReviveProofCandidatePlannerSmokeMarkdown")),
        "sourceBalanceRepairWorkorder": output_path(outputs.get("latestAudioSourceBalanceRepairWorkorderMarkdown")),
        "sourceBalanceRepairPreflight": output_path(outputs.get("latestAudioSourceBalanceRepairPreflightMarkdown")),
        "sourceBalanceRepairPreflightAudit": output_path(outputs.get("latestAudioSourceBalanceRepairPreflightAuditMarkdown")),
        "sourceBalanceRepairProofPlaylist": output_path(outputs.get("latestAudioSourceBalanceRepairProofPlaylist")),
        "listenPriorityNotesInbox": output_path(outputs.get("latestAudioListenPriorityNotesInboxMarkdown")),
        "speakerCleanupListenMapNotesInbox": output_path(outputs.get("latestSpeakerCleanupListenMapNotesInboxMarkdown")),
        "speakerCleanupListenMapNotesInboxSmoke": output_path(outputs.get("latestSpeakerCleanupListenMapNotesInboxSmokeMarkdown")),
        "listenNotesRepairPlanner": output_path(outputs.get("latestAudioListenNotesRepairPlannerMarkdown")),
        "postHumanListenNotesRoundtrip": output_path(outputs.get("latestAudioPostHumanListenNotesRoundtripMarkdown")),
        "postHumanListenNotesRoundtripSmoke": output_path(outputs.get("latestAudioPostHumanListenNotesRoundtripSmokeMarkdown")),
        "postHumanListenNotesRoundtripCommand": output_path(outputs.get("latestAudioPostHumanListenNotesRoundtripCommand")),
        "markerReviewNotesInbox": output_path(outputs.get("latestMarkerReviewNotesInboxMarkdown")),
        "markerReviewNotesInboxSmoke": output_path(outputs.get("latestMarkerReviewNotesInboxSmokeMarkdown")),
        "markerCommandPacket": output_path(outputs.get("latestMarkerReviewCommandPacketMarkdown")),
        "handoffIndex": output_path(outputs.get("latestReviewHandoffIndexMarkdown")),
        "readinessVerification": output_path(outputs.get("latestReviewReadinessVerificationMarkdown")),
    }

    commands = {
        "openMarkerConsole": open_command(paths["markerReviewConsole"], "marker review console"),
        "openReviewCockpit": open_command(paths["reviewCockpit"], "audio review cockpit"),
        "openVisualOverview": open_command(paths["visualOverviewHtml"] or paths["visualOverview"], "audio master visual overview"),
        "openProducerCommandCenter": open_command(paths["producerCommandCenterOpenCommand"] or paths["producerCommandCenterHtml"] or paths["producerCommandCenter"], "audio producer command center"),
        "openAudioRunwayState": open_command(paths["audioRunwayStateOpenCommand"] or paths["audioRunwayStateHtml"] or paths["audioRunwayState"], "audio runway state"),
        "openListenProofCoverageMap": open_command(paths["listenProofCoverageMapOpenCommand"] or paths["listenProofCoverageMapHtml"] or paths["listenProofCoverageMap"], "listen proof coverage map"),
        "openHumanApprovalPreflight": open_command(paths["humanApprovalPreflightOpenCommand"] or paths["humanApprovalPreflightHtml"] or paths["humanApprovalPreflight"], "audio human approval preflight"),
        "openHumanListenDecisionFrontDoor": open_command(paths["humanListenDecisionFrontDoorOpenCommand"] or paths["humanListenDecisionFrontDoorHtml"] or paths["humanListenDecisionFrontDoor"], "human listen decision front door"),
        "openPostListenOutcomeRouter": open_command(paths["postListenOutcomeRouterOpenCommand"] or paths["postListenOutcomeRouterHtml"] or paths["postListenOutcomeRouter"], "post-listen outcome router"),
        "openReviewerNotesTemplate": open_command(paths["reviewerNotesTemplateOpenCommand"] or paths["reviewerNotesTemplateHtml"] or paths["reviewerNotesTemplate"], "reviewer notes template"),
        "openBranchInheritanceGate": open_command(paths["branchInheritanceGateOpenCommand"] or paths["branchInheritanceGateHtml"] or paths["branchInheritanceGate"], "branch inheritance gate"),
        "openBranchRenderPreflight": open_command(paths["branchRenderPreflightOpenCommand"] or paths["branchRenderPreflightHtml"] or paths["branchRenderPreflight"], "branch render preflight"),
        "openApprovalPathSmoke": open_command(paths["approvalPathSmokeOpenCommand"] or paths["approvalPathSmoke"], "approval-path sandbox smoke"),
        "openUnresolvedRequirementReview": open_command(paths["unresolvedRequirementReviewOpenCommand"] or paths["unresolvedRequirementReviewHtml"] or paths["unresolvedRequirementReview"], "unresolved requirement review"),
        "openAudioProductionDoctrine": open_command(paths["audioProductionDoctrineOpenCommand"] or paths["audioProductionDoctrineHtml"] or paths["audioProductionDoctrine"], "audio production doctrine"),
        "openAudioTransformationLineageLedger": open_command(paths["audioTransformationLineageLedgerOpenCommand"] or paths["audioTransformationLineageLedgerHtml"] or paths["audioTransformationLineageLedger"], "audio transformation lineage ledger"),
        "openAudioTransformationLineageLedgerSmoke": open_command(paths["audioTransformationLineageLedgerSmokeOpenCommand"] or paths["audioTransformationLineageLedgerSmoke"], "audio transformation lineage ledger smoke"),
        "openStageControlSurface": open_command(paths["stageControlSurfaceOpenCommand"] or paths["stageControlSurfaceHtml"] or paths["stageControlSurface"], "audio workbench stage control surface"),
        "openProducerGradeAudit": open_command(paths["producerGradeAuditOpenCommand"] or paths["producerGradeAuditHtml"] or paths["producerGradeAudit"], "audio producer-grade audit"),
        "openPostReviewActionQueue": open_command(paths["postReviewActionQueue"], "audio post-review action queue"),
        "openRepairTuningConsole": open_command(paths["repairTuningConsoleOpenCommand"] or paths["repairTuningConsoleHtml"] or paths["repairTuningConsole"], "audio repair/tuning console"),
        "openParameterControlLedger": open_command(paths["parameterControlLedgerOpenCommand"] or paths["parameterControlLedgerHtml"] or paths["parameterControlLedger"], "audio parameter control ledger"),
        "openParameterSweepProofPlan": open_command(paths["parameterSweepProofPlanOpenCommand"] or paths["parameterSweepProofPlanHtml"] or paths["parameterSweepProofPlan"], "audio parameter sweep proof plan"),
        "openParameterSweepProofSnippetPack": open_command(
            paths["parameterSweepProofSnippetPackOpenCommand"]
            or paths["parameterSweepProofSnippetPackHtml"]
            or paths["parameterSweepProofSnippetPack"],
            "audio parameter sweep proof snippet pack",
        ),
        "openListenPriorityConsole": open_command(paths["listenPriorityConsole"], "audio listen-priority console"),
        "openListenPriorityQueue": open_command(paths["listenPriorityQueue"], "audio listen-priority queue"),
        "openListenPrioritySnippetPack": open_command(
            paths["listenPrioritySnippetPackOpenCommand"]
            or paths["listenPrioritySnippetPackHtml"]
            or paths["listenPrioritySnippetPack"],
            "audio listen-priority snippet pack",
        ),
        "openListenPriorityReviewReel": open_command(
            paths["listenPriorityReviewReelOpenCommand"]
            or paths["listenPriorityReviewReelHtml"]
            or paths["listenPriorityReviewReel"],
            "audio listen-priority review reel",
        ),
        "openFinalListenFastPass": open_command(
            paths["finalListenFastPassOpenCommand"]
            or paths["finalListenFastPassHtml"]
            or paths["finalListenFastPass"],
            "audio final listen fast pass",
        ),
        "openPlatformLoudnessAudit": open_command(
            paths["platformLoudnessAuditOpenCommand"]
            or paths["platformLoudnessAuditHtml"]
            or paths["platformLoudnessAudit"],
            "audio platform loudness audit",
        ),
        "openBroadcastPolishScorecard": open_command(
            paths["broadcastPolishScorecardOpenCommand"]
            or paths["broadcastPolishScorecardHtml"]
            or paths["broadcastPolishScorecard"],
            "audio broadcast polish scorecard",
        ),
        "openTechnicalAuditionSnippetPack": open_command(
            paths["technicalAuditionSnippetPackOpenCommand"]
            or paths["technicalAuditionSnippetPackHtml"]
            or paths["technicalAuditionSnippetPack"],
            "audio technical audition snippet pack",
        ),
        "runTechnicalAuditionNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            "python3 apps/QuipslyStudio/script/audio_workbench_technical_audition_notes_inbox.py --baseline-dir \"$OUT\"",
        ],
        "openSmoothnessProofPack": open_command(
            paths["smoothnessProofPackOpenCommand"]
            or paths["smoothnessProofPackHtml"]
            or paths["smoothnessProofPack"],
            "audio smoothness proof pack",
        ),
        "runSmoothnessProofNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            "python3 apps/QuipslyStudio/script/audio_workbench_smoothness_proof_notes_inbox.py --baseline-dir \"$OUT\"",
        ],
        "openHumanListenControlRoom": open_command(
            paths["humanListenControlRoomOpenCommand"]
            or paths["humanListenControlRoom"]
            or paths["humanListenControlRoomMarkdown"],
            "audio human listen control room",
        ),
        "openHumanListenDecisionBrief": open_command(
            paths["humanListenDecisionBrief"],
            "audio human listen decision brief",
        ),
        "openHumanListenDecisionRehearsal": open_command(
            paths["humanListenDecisionRehearsalOpenCommand"] or paths["humanListenDecisionRehearsal"],
            "human-listen decision rehearsal",
        ),
        "openSourceBalanceListenCompanion": open_command(
            paths["sourceBalanceListenCompanionOpenCommand"]
            or paths["sourceBalanceListenCompanion"],
            "audio source-balance listen companion",
        ),
        "openSpeakerContributionLedger": open_command(
            paths["speakerContributionLedgerOpenCommand"]
            or paths["speakerContributionLedgerHtml"]
            or paths["speakerContributionLedger"],
            "audio speaker contribution ledger",
        ),
        "openSpeakerPreservationProofPack": open_command(
            paths["speakerPreservationProofPackOpenCommand"]
            or paths["speakerPreservationProofPackHtml"]
            or paths["speakerPreservationProofPack"],
            "audio speaker preservation proof pack",
        ),
        "openSpeakerActivityReviewBoard": open_command(
            paths["speakerActivityReviewBoardHtml"] or paths["speakerActivityReviewBoard"],
            "audio speaker activity review board",
        ),
        "openSpeakerCleanupProofPack": open_command(
            paths["speakerCleanupProofPackHtml"] or paths["speakerCleanupProofPack"],
            "audio speaker cleanup proof pack",
        ),
        "openSpeakerCleanupProofPackAudit": open_command(
            paths["speakerCleanupProofPackAudit"],
            "audio speaker cleanup proof pack audit",
        ),
        "openSpeakerCleanupListenMap": open_command(
            paths["speakerCleanupListenMapOpenCommand"] or paths["speakerCleanupListenMapHtml"] or paths["speakerCleanupListenMap"],
            "audio speaker cleanup listen map",
        ),
        "openSpeakerCleanupDecisionMatrix": open_command(
            paths["speakerCleanupDecisionMatrixOpenCommand"] or paths["speakerCleanupDecisionMatrixHtml"] or paths["speakerCleanupDecisionMatrix"],
            "audio speaker cleanup decision matrix",
        ),
        "openAudioSpineListenSanity": open_command(
            paths["audioSpineListenSanity"],
            "audio spine listen sanity check",
        ),
        "openReusableAudioProductionProfile": open_command(
            paths["stableReusableAudioProductionProfile"] or paths["reusableAudioProductionProfile"],
            "reusable audio production profile",
        ),
        "openReusableAudioProductionProfileSmoke": open_command(
            paths["reusableAudioProductionProfileSmoke"],
            "reusable audio production profile smoke",
        ),
        "openDxReviveBouncePacket": open_command(
            paths["dxReviveManualBouncePacketOpenCommand"] or paths["dxReviveManualBouncePacket"],
            "dxRevive manual bounce packet",
        ),
        "openDxReviveReturnWorkbench": open_command(
            paths["dxReviveReturnWorkbenchOpenCommand"] or paths["dxReviveReturnWorkbenchHtml"] or paths["dxReviveReturnWorkbench"],
            "dxRevive return workbench",
        ),
        "openDxReviveBounceValidation": open_command(
            paths["dxReviveBounceValidation"],
            "dxRevive bounce validation",
        ),
        "openDxReviveBounceValidatorSmoke": open_command(
            paths["dxReviveBounceValidatorSmoke"],
            "dxRevive bounce validator smoke",
        ),
        "openDxReviveProofCandidatePlanner": open_command(
            paths["dxReviveProofCandidatePlanner"],
            "dxRevive proof candidate planner",
        ),
        "openDxReviveProofCandidatePlannerSmoke": open_command(
            paths["dxReviveProofCandidatePlannerSmoke"],
            "dxRevive proof candidate planner smoke",
        ),
        "openSourceBalanceRepairWorkorder": open_command(
            paths["sourceBalanceRepairWorkorder"],
            "audio source-balance repair workorder",
        ),
        "openSourceBalanceRepairPreflight": open_command(
            paths["sourceBalanceRepairPreflight"],
            "audio source-balance repair preflight",
        ),
        "openSourceBalanceProofComparison": [
            *open_command(paths["sourceBalanceRepairPreflightAudit"], "audio source-balance repair preflight audit"),
            *open_command(paths["sourceBalanceRepairProofPlaylist"], "audio source-balance repair proof playlist"),
        ],
        "checkStatus": [
            *open_command(paths["statusBoard"], "stable status board"),
            *open_command(paths["statusCheckCommand"], "status check command"),
        ],
        "runListenPriorityNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_listen_priority_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runPostHumanListenNotesRoundtrip": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_post_human_listen_notes_roundtrip.py --baseline-dir "$OUT"',
        ],
        "runMarkerNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_marker_review_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runSpeakerCleanupListenMapNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_speaker_cleanup_listen_map_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runSpeakerPreservationNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_speaker_preservation_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runFinalListenFastPassNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_final_listen_fast_pass_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runParameterSweepNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_parameter_sweep_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runProducerGradeNotesInbox": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_producer_grade_notes_inbox.py --baseline-dir "$OUT"',
        ],
        "runPostReviewActionQueue": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_post_review_action_queue.py --baseline-dir "$OUT"',
        ],
        "runListenNotesRepairPlanner": [
            "OUT=" + shell_quote(str(baseline_dir)),
            'python3 apps/QuipslyStudio/script/audio_workbench_listen_notes_repair_planner.py --baseline-dir "$OUT"',
        ],
    }

    md_path = baseline_dir / "START_HERE_EPISODE_4_AUDIO_REVIEW.md"
    command_path = baseline_dir / "OPEN_EPISODE_4_AUDIO_REVIEW.command"
    json_path = baseline_dir / "START_HERE_EPISODE_4_AUDIO_REVIEW.json"
    report = {
        "schema": "quipsly.audio-workbench.review-start-here.v1",
        "generatedAt": generated_at,
        "baselineDir": str(baseline_dir),
        "baselineId": baseline_id,
        "approvalStatus": manifest.get("approvalStatus"),
        "packageReadyForHumanListen": bool(manifest.get("packageReadyForHumanListen")),
        "humanListenStillRequired": not bool(manifest.get("branchInheritanceReady")),
        "branchInheritanceReady": bool(manifest.get("branchInheritanceReady")),
        "branchRenderReady": bool(manifest.get("branchRenderReady")),
        "paths": paths,
        "commands": commands,
        "markdownPath": str(md_path),
        "openCommandPath": str(command_path),
        "approvalStateChanged": False,
        "branchStateChanged": False,
        "renderAttempted": False,
        "originalMediaMutated": False,
    }
    md_path.write_text(build_markdown(report), encoding="utf-8")
    command_path.write_text(build_open_command(report), encoding="utf-8")
    os.chmod(command_path, 0o755)
    write_json(json_path, report)

    outputs["latestAudioReviewStartHere"] = str(json_path)
    outputs["latestAudioReviewStartHereMarkdown"] = str(md_path)
    outputs["latestAudioReviewStartHereOpenCommand"] = str(command_path)
    history = outputs.setdefault("audioReviewStartHerePackets", [])
    if str(json_path) not in history:
        history.append(str(json_path))
    manifest["audioReviewStartHereCount"] = len(history)
    write_json(manifest_path, manifest)

    print(
        json.dumps(
            {
                "baselineId": baseline_id,
                "markdown": str(md_path),
                "json": str(json_path),
                "openCommand": str(command_path),
                "approvalStateChanged": False,
                "branchStateChanged": False,
                "renderAttempted": False,
                "originalMediaMutated": False,
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
